name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload:
    name: Upload Code to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Code via Rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.KEY }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USER }}
          remote_path: /var/www/app

  deploy:
    name: Install Dependencies and Start Application on EC2
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: SSH into EC2 and Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/app
            pnpm install
            pnpm build
            pm2 describe website > /dev/null && pm2 reload pm2.json || pm2 start pm2.json